apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: devops-roadmap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: localhost:32000/devops-roadmap-frontend:latest
        imagePullPolicy: Always
        env:
        - name: VITE_API_URL
          value: "https://devops-roadmap-api.mukeshdev.online"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: devops-roadmap
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
